export interface IDrawables {
  splash: any,
  general: {
    Ic_Add: any;
    Ic_Advance: any;
    Ic_Arrow_Down: any;
    Ic_Arrow_Left: any;
    Ic_Arrow_Right: any;
    Ic_Arrow_Up: any;
    Ic_Arrows: any;
    Ic_Bell: any;
    Ic_Bike: any;
    Ic_Bus: any;
    Ic_storyIcon: any;
    Ic_Check: any;
    Ic_Chevron_Down: any;
    Ic_Chevron_Left: any;
    Ic_Chevron_Right: any;
    Ic_Chevron_Up: any;
    Ic_Circle: any;
    Ic_Clock: any;
    Ic_Close: any;
    Ic_Data_Protection: any;
    Ic_Data_Protection_Warn: any;
    Ic_Earth: any;
    Ic_Email: any;
    Ic_Error: any;
    Ic_Events: any;
    Ic_Eye: any;
    Ic_Eye_closed: any;
    Ic_Fee: any;
    Ic_filters: any;
    Ic_gotita: any;
    Ic_Heart: any;
    Ic_Home: any;
    Ic_Info: any;
    Ic_Map: any;
    Ic_Less: any;
    Ic_location: any;
    Ic_location_desactivated: any;
    Ic_Lock: any;
    Ic_LogOut: any;
    Ic_Meatballs: any;
    Ic_Ocupacion: any;
    Ic_open_eye: any;
    Ic_Plan: any;
    Ic_Play: any;
    Ic_Point_Dest: any;
    Ic_Point_MyLocation: any;
    Ic_Points: any;
    Ic_route: any;
    Ic_Real_Time: any;
    Ic_Refresh: any;
    Ic_Return: any;
    Ic_silla_compa: any;
    Ic_Search: any;
    Ic_Settings: any;
    Ic_Star: any;
    Ic_Success: any;
    Ic_Support: any;
    Ic_Transbordo: any;
    Ic_Up_bottomsheet: any;
    Ic_User: any;
    Ic_User_Circle: any;
    Ic_Walk: any;
    Ic_Warning: any;
    Ic_Warning_White: any;
    Ic_Wheelchair: any;
  }
}

export const drawables = {
  splash: {
    logo: require('@images/splashImage.png'),
  },
  general: {
    Ic_Add: require('@images/Ic_Add.png'),
    Ic_Advance: require('@images/Ic_Advance.png'),
    Ic_Arrow_Down: require('@images/Ic_Arrow_Down.png'),
    Ic_Arrow_Left: require('@images/Ic_Arrow_Left.png'),
    Ic_Arrow_Right: require('@images/Ic_Arrow_Right.png'),
    Ic_Arrow_Up: require('@images/Ic_Arrow_Up.png'),
    Ic_Arrows: require('@images/Ic_Arrows.png'),
    Ic_Bell: require('@images/Ic_Bell.png'),
    Ic_Bike: require('@images/Ic_Bike.png'),
    Ic_Bus: require('@images/Ic_Bus.png'),
    Ic_storyIcon: require('@images/Ic_storyIcon.png'),
    Ic_Check: require('@images/Ic_Check.png'),
    Ic_Chevron_Down: require('@images/Ic_Chevron_Down.png'),
    Ic_Chevron_Left: require('@images/Ic_Chevron_Left.png'),
    Ic_Chevron_Right: require('@images/Ic_Chevron_Right.png'),
    Ic_Chevron_Up: require('@images/Ic_Chevron_Up.png'),
    Ic_Circle: require('@images/Ic_Circle.png'),
    Ic_Clock: require('@images/Ic_clock.png'),
    Ic_Close: require('@images/Ic_Close.png'),
    Ic_Data_Protection: require('@images/Ic_Data_Protection.png'),
    Ic_Data_Protection_Warn: require('@images/Ic_Data_Protection_Warn.png'),
    Ic_Earth: require('@images/Ic_Earth.png'),
    Ic_Email: require('@images/Ic_Email.png'),
    Ic_Error: require('@images/Ic_Error.png'),
    Ic_Events: require('@images/Ic_Events.png'),
    Ic_Eye: require('@images/Ic_Eye.png'),
    Ic_Eye_closed: require('@images/Ic_Eye_closed.png'),
    Ic_Fee: require('@images/Ic_Fee.png'),
    Ic_filters: require('@images/Ic_filters.png'),
    Ic_gotita: require('@images/Ic_gotita.png'),
    Ic_Heart: require('@images/Ic_Heart.png'),
    Ic_Home: require('@images/Ic_Home.png'),
    Ic_Info: require('@images/Ic_Info.png'),
    Ic_Map: require('@images/Ic_Map.png'),
    Ic_Less: require('@images/Ic_Less.png'),
    Ic_location: require('@images/Ic_location.png'),
    Ic_location_desactivated: require('@images/Ic_location_desactivated.png'),
    Ic_Lock: require('@images/Ic_Lock.png'),
    Ic_LogOut: require('@images/Ic_LogOut.png'),
    Ic_Meatballs: require('@images/Ic_Meatballs.png'),
    Ic_Ocupacion: require('@images/Ic_Ocupacion.png'),
    Ic_open_eye: require('@images/Ic_open_eye.png'),
    Ic_Plan: require('@images/Ic_Plan.png'),
    Ic_Play: require('@images/Ic_Play.png'),
    Ic_Point_Dest: require('@images/Ic_Point_Dest.png'),
    Ic_Point_MyLocation: require('@images/Ic_Point_MyLocation.png'),
    Ic_Points: require('@images/Ic_Points.png'),
    Ic_route: require('@images/Ic_route.png'),
    Ic_Real_Time: require('@images/Ic_Real_Time.png'),
    Ic_Refresh: require('@images/Ic_Refresh.png'),
    Ic_Return: require('@images/Ic_Return.png'),
    Ic_silla_compa: require('@images/Ic_silla_compa.png'),
    Ic_Search: require('@images/Ic_Search.png'),
    Ic_Settings: require('@images/Ic_Settings.png'),
    Ic_Star: require('@images/Ic_Star.png'),
    Ic_Success: require('@images/Ic_Success.png'),
    Ic_Support: require('@images/Ic_Support.png'),
    Ic_Transbordo: require('@images/Ic_Transbordo.png'),
    Ic_Up_bottomsheet: require('@images/Ic_Up_bottomsheet.png'),
    Ic_User: require('@images/Ic_User.png'),
    Ic_User_Circle: require('@images/Ic_User_Circle.png'),
    Ic_Walk: require('@images/Ic_Walk.png'),
    Ic_Warning: require('@images/Ic_Warning.png'),
    Ic_Warning_White: require('@images/Ic_Warning_White.png'),
    Ic_Wheelchair: require('@images/Ic_Wheelchair.png'),
  }
};
