/***
 * Formato de literales: [pantalla]_[lineral]
 */

export const strings = {
  accessibility_button_back_label: 'Flecha Atrás',
  accessibility_button_back_desc: 'Al pulsarlo vuelves a la pantalla anterior',
  accessibility_search_item_main_desc: 'Al pulsar sobre el elemento se presenta en el mapa y su información detallada',
  accessibility_search_stops_lines: 'Listado de paradas y líneas',
  accessibility_filters_section_list: 'Listado de filtros',
  accessibility_filters_transports: 'Listado de filtros de modos de transporte',
  accessibility_filters_transports_desc: 'Al pulsar sobre un elemento filtra los marcadores de paradas de transporte en el mapa',
  button_accept: 'Aceptar',
  button_cancel: 'Cancelar',
  button_confirm: 'Confirmar',
  button_undo: 'Deshacer',
  filters_title: 'Filtros',
  filters_section_transport: 'Transporte',
  input_button_clear: 'Borrar texto',
  input_button_clear_description: 'Al pulsarlo borra el texto escrito',
  input_icon_search: 'Lupa',
  location_activate_title: 'Activa tu geolocalización',
  location_activate_description: 'Activa tu geolocalización para tener una mejor experiencia',
  location_activate_blocked_title: 'Permite el acceso a tu ubicación',
  location_activate_blocked_description: 'El permiso de acceso a la ubicación se encuentra bloqueado por favor acéptelo para poder acceder a su ubicación.',
  marker_myLocation: 'Ubicación actual',
  planner_screen_title: '¿A donde quieres ir?',
  planner_segments_origin_placeholder: 'Busca un origen',
  planner_segments_destination_placeholder: 'Busca un destino',
  search_screen_title: '¿Qué estas buscando?',
  search_bar_placeholder: 'Parada o destino',
  search_recents_title: 'Búsquedas recientes',
  search_recents_empty: 'Busca una dirección o selecciona un...',
  search_empty: 'No se han encontrado resultados',
  search_stops_lines: 'Paradas y líneas',
  splash_title:  'Bienvenidos a la nueva app de EMT Palma',
  settings_screen_title: 'Configuración',
  settings_section_general: 'General',
  settings_section_general_login: 'Iniciar sesión',
  settings_section_general_signup: 'Crear cuenta',
  settings_section_general_language: 'Idioma',
  settings_section_general_accessibility: 'Accesibilidad',
  settings_section_general_data_protection: 'Protección de datos',
  settings_section_general_legal_notice: 'Aviso legal',
  settings_section_general_cookies: 'Política de cookies',
  settings_section_gam: 'Gamificación',
  settings_section_gam_gamification: 'Ludificación',
  settings_section_gam_involvement: 'Participación',
  settings_section_help: 'Ayuda',
  settings_section_help_support: 'Soporte',
  settings_section_help_contact: 'Contacto',
  language_ca: 'Catalán',
  language_es: 'Español',
  language_en: 'Inglés',
  topSearchBar_title: 'Parada o destino',
};
