/***
 * Formato de literales: [pantalla]_[lineral]
 */

export const strings = {
  accessibility_button_back_label: 'Flecha Atrás',
  accessibility_button_back_desc: 'Al pulsarlo vuelves a la pantalla anterior',
  accessibility_button_delete: 'Equis borrar',
  accessibility_button_delete_desc: 'Al pulsarlo borra el contenido',
  accessibility_search_item_main_desc: 'Al pulsar sobre el elemento se presenta en el mapa y su información detallada',
  accessibility_search_stops_lines: 'Listado de paradas y líneas',
  accessibility_filters_section_list: 'Listado de filtros',
  accessibility_filters_transports: 'Listado de filtros de modos de transporte',
  accessibility_filters_transports_desc: 'Al pulsar sobre un elemento filtra los marcadores de paradas de transporte en el mapa',
  accessibility_calendar_name: 'Calendario',
  accessibility_calendar_planner_desc: 'Al pulsar sobre un día se selecciona como el día para planificar el viaje',
  accessibility_calendar_month_next: 'Al pulsar presenta el siguiente mes',
  accessibility_calendar_month_previous: 'Al pulsar presenta al mes anterior',
  accessibility_calendar_modal_desc: 'Al pulsarse presenta un seleccionador de la fecha en forma de calendario',
  accessibility_directory_lines: 'Listado de líneas',
  accessibility_hour_modal: 'Al pulsarse presenta un modal con un seleccionador de la hora',
  accessibility_hour_selector_label: 'Lista de los números de la hora',
  accessibility_hour_selector_desc: 'Desliza los dos dedos hacia arriba o abajo para seleccionar el número de la hora',
  accessibility_minute_selector_label: 'Lista de los números de los minutos',
  accessibility_minute_selector_desc: 'Desliza los dos dedos hacia arriba o abajo para seleccionar el número de los minutos',
  accessibility_planner_result_cards: 'Listado de itinerarios planificados.',
  accessibility_planner_segments_desc: 'Al pulsarlo navega al buscador para selecciona un punto.',
  accessibility_planner_segments_change: 'Cambio de sentido',
  accessibility_planner_segments_change_desc: 'Al pulsarlo intercambia entre sí el punto de origen y destino.',
  accessibility_planner_preferences_button_desc: 'Al pulsarlo presenta los filtros de preferencias del planificador.',
  accessibility_planner_preferences_button_undo: 'Al pulsarlo deshace las preferencias seleccionadas del planificador.',
  accessibility_planner_preferences_button_confirm: 'Al pulsarlo guarda los cambios de las preferencias seleccionadas',
  accessibility_planner_preferences_filter_accessibility_desc: 'Al pulsarlo selecciona si se desean rutas accesibles para sillas de ruedas.',
  accessibility_planner_preferences_filter_disuasorio_desc: 'Al pulsarlo selecciona si se desean rutas en las que haya un parking disuasorio.',
  accessibility_planner_preferences_filter_interchange_desc: 'Al pulsarlo selecciona si se desean rutasen las que haya un parking de intercambio.',
  accessibility_planner_preferences_operators: 'Listado de filtros por operadores del planificador.',
  accessibility_planner_preferences_operators_desc: 'Al pulsar filtra mediante ese operador al planificar',
  accessibility_planner_timer_button_desc: 'Al pulsarlo presenta una lista de tipos de momentos en el tiempo para poder planificar',
  accessibility_planner_timer_now_button_desc: 'Tras pulsarse la planificación tomará como hora de salida la actual.',
  accessibility_planner_timer_departure_button_desc: 'Tras pulsarse la planificación tomará como fecha y hora de salida la que se establezca en el selector.',
  accessibility_planner_timer_arrival_button_desc: 'Tras pulsarse la planificación tomará como fecha y hora de llegada la que se establezca en el selector.',
  accessibility_planner_timer_itinerary_hour: 'Hora itinerario',
  accessibility_planner_card_warning: 'Alerta',
  accessibility_planner_card_legs: 'Listado de tramos de ruta',
  accessibility_planner_card_leg_walk: 'Tramo ruta andando, duración',
  accessibility_planner_card_leg_transfer: 'Transbordo, duración',
  accessibility_planner_card_leg_trip: 'Tramo ruta',
  accessibility_duration: 'duración',
  button_accept: 'Aceptar',
  button_cancel: 'Cancelar',
  button_confirm: 'Confirmar',
  button_done: 'Hecho',
  button_save: 'Guardar',
  button_undo: 'Deshacer',
  component_loading: 'Cargando',
  filters_title: 'Filtros',
  filters_section_transport: 'Transporte',
  input_button_clear: 'Borrar texto',
  input_button_clear_description: 'Al pulsarlo borra el texto escrito',
  input_icon_search: 'Lupa',
  line: 'Línea',
  line_schedule: 'Horarios',
  line_alert: 'Avisos',
  location_activate_title: 'Activa tu geolocalización',
  location_activate_description: 'Activa tu geolocalización para tener una mejor experiencia',
  location_activate_blocked_title: 'Permite el acceso a tu ubicación',
  location_activate_blocked_description: 'El permiso de acceso a la ubicación se encuentra bloqueado por favor acéptelo para poder acceder a su ubicación.',
  marker_myLocation: 'Ubicación actual',
  minutes: 'minutos',
  planner_accessibility: 'Accesibilidad',
  planner_accessibility_checkbox: 'Accesibilidad para silla de ruedas',
  planner_parking_disuasorio_checkbox: 'Parking disuasorio',
  planner_parking_interchange_checkbox: 'Parking de intercambio',
  planner_preferences: 'Preferencias',
  planner_preferences_filter_operators: 'Operadores',
  planner_preferences_filter_route_type: 'Tipo de ruta',
  planner_preferences_filter_route_parameters: 'Parámetros',
  planner_preferences_filter_route_type_fast: 'Más rápida',
  planner_preferences_filter_route_type_transfer: 'Menos transbordo',
  planner_preferences_filter_route_type_walk: 'Caminar menos',
  planner_result_empty_title: 'No se han encontrado resultados',
  planner_result_empty_desc: 'Si desea obtener una planificación modifique las preferencias o los puntos de salida o llegada',
  planner_result_card_order_fast: 'Ruta más rápida',
  planner_result_card_order_transfer: 'Menos transbordos',
  planner_result_card_order_walk: 'Andar menos',
  planner_route_departure: 'Salir en',
  planner_screen_title: '¿A donde quieres ir?',
  planner_segments_origin: 'Origen',
  planner_segments_origin_placeholder: 'Busca un origen',
  planner_segments_destination: 'Destino',
  planner_segments_destination_placeholder: 'Busca un destino',
  planner_timer_arrive: 'Llegar a las',
  planner_timer_departure: 'Salir a las',
  planner_timer_now: 'Salir ahora',
  planner_transfer: 'Transbordo',
  search_screen_title: '¿Qué estas buscando?',
  search_bar_placeholder: 'Parada o destino',
  search_directories: 'Directorios',
  search_directories_lines: 'Listado de líneas',
  search_directories_lines_title: 'Directorio de líneas',
  search_directories_lines_bar: 'Busca una línea',
  search_recents_title: 'Búsquedas recientes',
  search_recents_empty: 'Busca una dirección o selecciona un punto en el mapa que te permita realizar una planificación',
  search_empty: 'No se han encontrado resultados',
  search_stops_lines: 'Paradas y líneas',
  splash_title:  'Bienvenidos a la nueva app de EMT Palma',
  settings_screen_title: 'Menú',
  settings_section_general: 'General',
  settings_section_general_account: 'Gestionar cuenta',
  settings_section_general_alert: 'Avisos',
  settings_section_general_fee: 'Tarifas',
  settings_section_general_login: 'Iniciar sesión',
  settings_section_general_signup: 'Crear cuenta',
  settings_section_general_language: 'Idioma',
  settings_section_general_accessibility: 'Accesibilidad',
  settings_section_general_data_protection: 'Protección de datos',
  settings_section_general_legal_notice: 'Aviso legal',
  settings_section_general_cookies: 'Política de cookies',
  settings_section_general_settings: 'Configuración',
  settings_section_points: 'Mis puntos',
  settings_section_gam: 'Gamificación',
  settings_section_gam_gamification: 'Ludificación',
  settings_section_gam_involvement: 'Participación',
  settings_section_help_and_support: 'Soporte y ayuda',
  settings_section_help: 'Ayuda',
  settings_section_help_support: 'Soporte',
  settings_section_help_contact: 'Contacto',
  language_ca: 'Catalán',
  language_es: 'Español',
  language_en: 'Inglés',
  timer_at: 'a las',
  timer_arrival: 'Llegada',
  timer_departure: 'Salida',
  topSearchBar_title: 'Parada o destino',
  months: {
    1: 'Enero',
    2: 'Febrero',
    3: 'Marzo',
    4: 'Abril',
    5: 'Mayo',
    6: 'Junio',
    7: 'Julio',
    8: 'Agosto',
    9: 'Septiembre',
    10: 'Octubre',
    11: 'Noviembre',
    12: 'Diciembre',
  },
  monthsAbrev: {
    1: 'En.',
    2: 'Feb.',
    3: 'Mar.',
    4: 'Abr.',
    5: 'May.',
    6: 'Jun.',
    7: 'Jul.',
    8: 'Agos.',
    9: 'Sept.',
    10: 'Oct.',
    11: 'Nov.',
    12: 'Dic.',
  },
  weekDays: {
    0: 'Domingo',
    1: 'Lunes',
    2: 'Martes',
    3: 'Miercoles',
    4: 'Jueves',
    5: 'Viernes',
    6: 'Sabado',
  },
  weekDaysAbrev: {
    0: 'Dom.',
    1: 'Lun.',
    2: 'Ma.',
    3: 'Mier.',
    4: 'Jue.',
    5: 'Vie.',
    6: 'Sab.',
  },
};
